# Generated by Django 3.2 on 2021-05-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lisshop', '0004_alter_products_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='products_currency',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='product_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_date',
            field=models.DateField(),
        ),
    ]
